
services:
  freeradius:
    container_name: freeradius
    build: .
    command: -X
    extra_hosts:
      - "host.docker.internal:host-gateway"
       # volumes:
      # - ./radius-config:/etc/raddb
    restart: unless-stopped
    networks:
      - bans-network
    labels:
      - "traefik.enable=true"

      # For Authentication
      - "traefik.udp.routers.radius-auth.rule=HostSNI(`*`)"
      - "traefik.udp.routers.radius-auth.entrypoints=radius-auth"
      - "traefik.udp.routers.radius-auth.service=freeradius-auth"
      - "traefik.udp.services.freeradius-auth.loadbalancer.server.port=1812"

      # For Accounting
      - "traefik.udp.routers.radius-acct.rule=HostSNI(`*`)"
      - "traefik.udp.routers.radius-acct.entrypoints=radius-acct"
      - "traefik.udp.routers.radius-acct.service=freeradius-acct"
      - "traefik.udp.services.freeradius-acct.loadbalancer.server.port=1813"  
networks:
  bans-network:
    external: true
