services: 
  portal-web:
    restart: always
    build: .
    environment:
      - ./env
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.portal-backend.rule=Host(`portal-backend.umbiro.com`)"
      - "traefik.http.routers.portal-backend.entrypoints=websecure"
      - "traefik.http.routers.portal-backend.tls.certresolver=letsencrypt"
      - "traefik.http.services.portal-backend.loadbalancer.server.port=3005"
    networks:
        - dokploy-network
networks:
  dokploy-network:
    external: true
